name: Aircraft Accident Lawyer
favicon: null
layout_spectrum: 0.6761802551336586
typography_spectrum: 0.7037041217554361
title: Aircraft Accident Lawyer - News and Tips
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77288-93
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7090682312846184
  lightness: 0.557458135066554
  saturation: 0.0066983450669795275
  rhythmicContrast: 0.6541645133402199
purpose: []
