name: Aircraft Accident Lawyer
favicon: null
layout_spectrum: 0.7623
typography_spectrum: 0.7037041217554361
title: Aircraft Accident Lawyer - News and Tips
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77288-93
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c4f58'
    - '#29272d'
    - '#fefefe'
    - '#6a8b7a'
    - '#9e9c8e'
  brandStrength: 0.7090682312846184
  lightness: 0.557458135066554
  saturation: 0.0066983450669795275
  rhythmicContrast: 0.6541645133402199
purpose: []
